export default {
    Apps_Url: '/ypages',
    Apps_Title: 'Yellow Pages',
    Form_Group_Title: 'Group (Index) - Form',
    Form_Contact_Title: 'Contact Form',
    Apps_Logo: 'fa-solid fa-book',
    Icon_Close: 'fa-solid fa-xmark',
    Icon_AddNew: 'fa-solid fa-file',
    Icon_Save: 'fa-solid fa-floppy-disk',
    Icon_Delete: 'fa-solid fa-trash',
    Icon_Groups: 'fa-solid fa-folder-tree',
    Icon_Group: 'fa-solid fa-folder',
    Icon_Contact: 'fa-solid fa-address-card',
    Icon_Badge: 'fa-solid fa-id-badge',
    Icon_Mobile: 'fa-solid fa-mobile-retro',
    Icon_Plus: 'fa-solid fa-plus',
    Icon_EOF: 'fa-solid fa-asterisk',
    Icon_Search: 'fa-solid fa-magnifying-glass',
    Icon_Filter: 'fa-solid fa-filter-circle-xmark',
    API_Request_4Index: 1,
    API_Request_4Group: 2,
    API_Request_4Contact: 3,
    ICRUD_Index: 0,
    ICRUD_Create: 1,
    ICRUD_Read: 2,
    ICRUD_Update: 3,
    ICRUD_Delete: 4,
    Slug_Defualt: 'blank',
    MSG_Default_Msg: 'Fill all fields',
    MSG_FillAllNextField: 'Fill all fields for next record',
    MSG_Processing: 'Processing, please wait...',
    MSG_Default: 0,
    MSG_Success: 1,
    MSG_Failure: 2,
    MSG_Loading: 3,
    MSG_Class: ['alert-info', 'alert-success', 'alert-danger', 'alert-warning'],
    MSG_Icon: ['fa-solid fa-circle-info', 'fa-solid fa-check', 'fa-solid fa-triangle-exclamation', 'fa-solid fa-spinner'],
    MSG_Delete: 'Are you sure you wish to delete?',
    MSG_DeletedSuccessfully: 'Deleted successfully',
    MSG_SavedSuccessfully: 'Saved successfully'
}