SLUG_SPLIT = "xz-qy-wu"
SLUG_DEFAULT = "blank"
API_REQUEST_4INDEX = 1
API_REQUEST_4GROUP = 2
API_REQUEST_4CONTACT = 3

ICRUD_INDEX = 0
ICRUD_CREATE = 1
ICRUD_READ = 2
ICRUD_UPDATE = 3
ICRUD_DELETE = 4
